baseURL = 'https://dynamy-ai.github.io/'
languageCode = 'en-us'
title = 'Dynamy.Ai'

theme="hugo-PaperMod"

[params]
  [params.homeInfoParams]
    Title = "Hi there wave"
    Content = "Can be Info, links, about..."



  [params.profileMode]
    enabled = "true"
    title = "Long lasting effeciencies using AI"
    imageUrl: "/images/logo.png"
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size